project:
  type: website

  resources:
    - "pgp_clin.asc.txt"
    - "html/fonts/"
    - "html/vendor/"

freeze: auto

pagetitle: "{{< meta title >}} | Chunyi Lin"
author-meta: "Chunyi Lin"

# Date format
date-format: "dddd, MMMM D, YYYY"

website:
  description: "Chunyi Lin is an undergraduate psychology student at Zhejiang University, with his research interests in cognitive sciences."
  favicon: favicon.svg
  site-url: https://www.chunyi-lin.com
  repo-url: "https://github.com/c-lin-chunyi/blog"
  title: "Chunyi Lin"

  llms-txt: true

  navbar:
    logo: logo.svg
    pinned: true
    left:
      - text: CV
        href: cv/index.qmd
      - text: Posts
        href: posts/index.qmd
      - text: AI Usage Disclosure
        href: ai/index.qmd
    right:
      - icon: github
        href: https://github.com/c-lin-chunyi
      - icon: envelope
        href: mailto:c.lin.chunyi@gmail.com
  page-footer:
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} {{< var years >}} {{< var author-name >}}</span>
      <span class="faux-block">All content licensed under<br>[{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} Creative Commons {{< var license.name >}}]({{< var license.url >}})</span>
    center: |
      <span class="faux-block">{{< fa brands orcid >}} <strong>ORCID</strong> [{{< var orcid >}}](https://orcid.org/{{< var orcid >}})</span>
      <span class="faux-block">{{< fa key >}} [PGP public key]({{< var pgp.key >}}) &emsp; {{< fa fingerprint >}} <strong>Fingerprint:</strong><br><span class="fingerprint">{{< var pgp.fingerprint >}}</span></span>
    right: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>
      <span class="faux-block">[View the source at {{< fa brands github >}} GitHub](https://github.com/c-lin-chunyi/blog)</span>

format:
  html:
    theme:
      light: html/light.scss
      dark: html/dark.scss
    respect-user-color-scheme: true
    html-math-method:
      method: mathjax
      url: "html/vendor/mathjax-4.0.0/startup.js"
    include-in-header:
      - html/fonts.html
      - html/mathjax-stix.html
      - html/theme-toggle.html
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
